# Generated by Django 6.1 on 2026-09-06 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0009_rtstructroi_roi_segmentation_username_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_sessions', to='app.dicomseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified_at'],
                'unique_together': {('user', 'image_series')},
            },
        ),
        migrations.CreateModel(
            name='UserSegmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi_name', models.CharField(max_length=255)),
                ('labelmap_data', models.BinaryField(blank=True, null=True)),
                ('labelmap_shape', models.JSONField(blank=True, null=True)),
                ('finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rtstruct_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_segmentations', to='app.dicominstance')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentations', to='segmentation.segmentationsession')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
    ]
