# Generated by Django 6.0.3 on 2026-03-08 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtstructroi',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dicominstance'),
        ),
        migrations.AddConstraint(
            model_name='rtstructroi',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('instance__isnull', False), ('staple_roi__isnull', True)), models.Q(('instance__isnull', True), ('staple_roi__isnull', False)), _connector='OR'), name='either_instance_or_staple_roi'),
        ),
    ]
