# Generated by Django 6.0.3 on 2026-03-08 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dicominstance_referenced_series_instance_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicominstance',
            name='referenced_series_instance_uid',
            field=models.ForeignKey(blank=True, help_text='This is the reference series instance UID for the RTStruct File only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_series_uid', to='app.dicomseries'),
        ),
    ]
