# Generated by Django 6.0.3 on 2026-03-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dicominstance_referenced_series_instance_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomseries',
            name='nifti_file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
