# Generated by Django 6.0.3 on 2026-03-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_stapleroi_staple_roi_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicominstance',
            name='structure_set_label',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='rtstructroi',
            name='roi_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='rtstructroi',
            name='roi_generation_algorithm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
